[metadata]
format.version = "1.1"

[versions]
assertj = "3.27.6"
awaitility = "4.2.0"
junit = "6.0.2"
jackson = "2.21.0"
jakarta-json = "2.1.3"
parsson = "1.1.7"
jupiter = "6.0.2"
okhttp = "5.3.0"
mockito = "5.21.0"
tck = "1.0.0-SNAPSHOT"
titanium = "1.7.0"
schema-validator = "2.0.1"

[libraries]

# modules from tck-common
tck-common-api = { module = "org.eclipse.dataspacetck.common:core-api", version.ref = "tck" }

assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-jsonp = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jakarta-jsonp", version.ref = "jackson" }
json-api = { module = "jakarta.json:jakarta.json-api", version.ref = "jakarta-json" }
parsson = { module = "org.eclipse.parsson:parsson", version.ref = "parsson" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "jupiter" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-suite-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
titanium = { module = "com.apicatalog:titanium-json-ld", version.ref = "titanium" }
schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "schema-validator" }

[plugins]
docker = { id = "com.bmuschko.docker-remote-api", version = "10.0.0" }
shadow = { id = "com.gradleup.shadow", version = "9.3.1" }
nexuspublishing = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
tck-build = { id = "org.eclipse.dataspacetck.build.tck-build", version.ref = "tck" }
tck-generator = { id = "org.eclipse.dataspacetck.build.tck-build", version.ref = "tck" }
